# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23536e4eaf4d160ee0c74722dec074551336530718391b933fe9d4590a98e0908af65fc4d195893d7108868f4036c9564ed77aa64cb48574483d01a934d3f1a9

test:
  secret_key_base: 2d334bf8e06319cc43cebf4088a3bff6e17f96b507ad722bba8c44e5276ee4b9ba16f452a6b94bbc62a59cdc920126bd914dfd73436fe8b5830a32b44805b55a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
